---
version: "3.4"
services:
  postgres:
    build:
      context: ./postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=password
  go:
    build:
      context: ./go
    depends_on:
      - postgres
    environment:
      - PG_CONN=postgresql://postgres:password@postgres:5432/postgres?sslmode=disable
    volumes:
      - .:/app
      - gopkg:/go/pkg
    working_dir: /app
    command:
      - go
      - test
      - github.com/cicdata-io/casbin-pgx-adapter

volumes:
  gopkg:
